# Generated by Django 5.0 on 2024-03-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('singer', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=100)),
                ('Images', models.ImageField(upload_to='Images')),
                ('song', models.FileField(upload_to='Images')),
            ],
        ),
    ]
