# Generated by Django 5.0 on 2024-03-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('Artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('bio', models.TextField(blank=True)),
                ('Images', models.ImageField(upload_to='Images')),
                ('song', models.FileField(upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('Images', models.ImageField(upload_to='Images')),
                ('song', models.FileField(upload_to='Images')),
            ],
        ),
    ]
